import { formatFullDate, formatNGN } from '@/lib/format';
import { lineTotal } from '@/lib/money';
import type { Invoice } from '@/lib/types';
import { StatusBadge } from './status-badge';
import { InvoicePdfButton } from './invoice-pdf-button';
import { invoiceStatus } from '@/lib/invoices';
export function InvoicePreview({ invoice }: { invoice: Invoice }) {
  return <article className="invoice-preview" aria-label={`Invoice ${invoice.number ?? invoice.id}`}><header><div><p className="eyebrow">OLIVE & STITCH</p><h3>{invoice.number ?? invoice.id}</h3></div><StatusBadge status={invoiceStatus(invoice)} /></header><div className="invoice-address"><div><span>Bill to</span><strong>{invoice.customer}</strong><p>{invoice.email}</p></div><div><span>Due date · Lagos</span><strong>{formatFullDate(invoice.dueAt)}</strong></div></div><div className="table-scroll" tabIndex={0} role="region" aria-label="Invoice line items"><table><caption className="sr-only">Invoice line items</caption><thead><tr><th scope="col">Description</th><th scope="col">Qty</th><th scope="col">Unit price</th><th scope="col">Total</th></tr></thead><tbody>{invoice.items?.map((item, index) => <tr key={index}><td>{item.description}</td><td>{item.quantity}</td><td className="amount-cell">{formatNGN(item.unitPriceKobo)}</td><td className="amount-cell">{formatNGN(lineTotal(item) ?? 0)}</td></tr>)}</tbody></table></div><div className="invoice-total"><span>Total · NGN</span><strong>{formatNGN(invoice.amountKobo)}</strong></div>{invoice.notes && <div className="invoice-notes"><h4>Notes</h4><p>{invoice.notes}</p></div>}{invoice.transactionId && <p className="date-note">Paid by sample transaction {invoice.transactionId}. No real payment occurred.</p>}<p className="invoice-disclaimer">Demo invoice · No payment is requested. Status is evaluated as of 8 October 2026.</p><InvoicePdfButton invoice={invoice} /></article>;
}
