import Link from 'next/link';
import { ArrowUpRight, CreditCard, Landmark } from 'lucide-react';
import { formatDate, formatNGN } from '@/lib/format';
import type { Transaction } from '@/lib/types';
export function TransactionList({ transactions }: { transactions: Transaction[] }) {
  return <section className="card transactions-card" aria-labelledby="recent-title"><div className="section-heading"><div><h2 id="recent-title">Recent transactions</h2><p>Your five latest payments in this period</p></div><Link className="text-link" href="/transactions">View all transactions <ArrowUpRight size={15} aria-hidden="true" /></Link></div>
    {transactions.length === 0 ? <div className="empty-state"><h3>No transactions in this period</h3><p>Choose a longer reporting period to explore more sample payments.</p></div> : <div className="table-scroll" role="region" aria-label="Recent transactions table, scroll horizontally for more columns" tabIndex={0}><table className="transactions-table"><caption className="sr-only">Five most recent transactions in the selected period</caption><thead><tr><th scope="col">Customer / reference</th><th scope="col">Amount</th><th scope="col">Status</th><th scope="col">Method</th><th scope="col">Date</th></tr></thead><tbody>{transactions.map(t => <tr key={t.id}><td><div className="customer-cell"><span className="customer-avatar" aria-hidden="true">{t.customer.split(' ').map(s => s[0]).join('')}</span><div><strong>{t.customer}</strong><small>{t.reference}</small></div></div></td><td className="amount-cell">{formatNGN(t.amountKobo)}</td><td><span className={`status-badge ${t.status}`}><span aria-hidden="true" />{t.status === 'successful' ? 'Successful' : t.status === 'pending' ? 'Pending' : 'Failed'}</span></td><td><span className="payment-method">{t.method === 'card' ? <CreditCard size={15} aria-hidden="true" /> : <Landmark size={15} aria-hidden="true" />}{t.method === 'card' ? 'Card' : 'Bank transfer'}</span></td><td>{formatDate(t.timestamp)}</td></tr>)}</tbody></table></div>}
  </section>;
}
